### ISSUE TITLE
Source code and license

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [apollographql/apollo-studio-preview-docs#2]
Will the source code be open and if so under terms of what license?

**Comment by ndintenfass** [comment]
We don't yet have plans to open the source, as this is currently built into our hosted application. Use will be through the existing Apollo TOS as a service for now. We are interested in feedback from folks about whether it will be important for them to run their own instance of these tools, but our initial focus is on folks who will value having it ready to go, already connected to their registered graphs and able to open up stateful sharing possibilities out of the box, so for the near term you'll see Studio only as a hosted cloud app.

**Comment by FluorescentHallucinogen** [comment]
Apollo Studio would be very useful as a separate tool.

Since GraphQL Playground was merged with (actually, was deprecated in favor of) GraphiQL (https://foundation.graphql.org/news/2020/04/03/web-based-graphql-ides-for-the-win-how-why-playground-graphiql-are-joining-forces/), it would be really nice for the whole GraphQL community to have another open-source GraphQL IDE for competition and diversity.

@acao cc.

**Comment by acao** [comment]
@FluorescentHallucinogen there are many open source IDEs using our LSP and codemirror mode, whether playground, insomnia, altair, etc. I'm releasing the new monaco-graphql there too, so theres nothing stopping anyone. What's more, you can easily fork playground to create an awesome competing tool!

**Comment by acao** [comment]
@FluorescentHallucinogen `monaco-graphql` has been released, if you want to build a competing tool with any javascript library or framework, it will be a great starting point! I welcome it because, like with `codemirror-graphql`, we all stand to benefit as we improve our shared dependencies.

**Comment by shellscape** [comment]
checking in here to say that I'm truly disappointed in Apollo's decision to keep the explorer closed source. It's an unfortunate move for a company that's traditionally embraced open source to the _fullest extent_.
